# Generated by Django 4.2.7 on 2026-04-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_user__temp_migration_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='work_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
